"""
Generate split-free robot→robot identity reconstruction pairs from segment data.

For each 4s segment, creates 4 self-reconstruction 1s pairs where the
control_video is byte-for-byte identical to the target video:
  clip_0→clip_0, clip_1→clip_1, clip_2→clip_2, clip_3→clip_3

The control mp4 is generated by `shutil.copyfile` of the target mp4 so that
mitty_cache.py's downstream VAE encoding produces human_latent == robot_latent
(stage1 robot reconstruction).

Output is organized by semantic data type, duration, and robot task so
mitty_cache.py can build split-free per-task caches.

Usage:
  # Formal identity data: --task all expands to TRAINING_TASKS only.
  python -m src.pipeline.make_robot_pair --task all --max-segments 500 --clean

  python -m src.pipeline.make_robot_pair --task all --max-segments 50 \
    --workers 8

  # Historical/debug data outside TRAINING_TASKS must be requested explicitly.
  python -m src.pipeline.make_robot_pair --task inspire --max-segments 50
"""

import argparse
import csv
import json
import os
import random
import re
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.stdout.reconfigure(line_buffering=True)

from src.core.config import ALL_TASKS, PAIR_DIR, SEGMENT_DIR, TRAINING_TASKS

FFMPEG = os.environ.get(
    "FFMPEG_BIN",
    "/home/leadtek/miniconda3/envs/flip/bin/ffmpeg",
)

TARGET_FPS = 16
NUM_FRAMES = 17
PROMPT = "A first-person view robot arm performing household tasks flip_v2v"
SEGMENT_DURATION = 4.0
CLIP_DURATION = 1.0
CLIPS_PER_SEG = int(SEGMENT_DURATION / CLIP_DURATION)  # 4


def _ffmpeg(args: list[str]):
    subprocess.check_call(
        [FFMPEG, "-y"] + args,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def cut_clip(segment_video: str, out_path: str, start: float):
    _ffmpeg([
        "-ss", f"{start:.3f}", "-i", segment_video,
        "-t", f"{CLIP_DURATION + 0.5:.3f}",
        "-r", str(TARGET_FPS),
        "-frames:v", str(NUM_FRAMES),
        "-c:v", "libx264", "-crf", "18", "-preset", "fast",
        "-an", out_path,
    ])


# ── segment discovery ────────────────────────────────────────────────

def find_segments(tasks: list[str]) -> list[dict]:
    segments = []
    for task in tasks:
        task_dir = os.path.join(SEGMENT_DIR, task)
        if not os.path.isdir(task_dir):
            continue
        for root, _, files in os.walk(task_dir):
            for fname in sorted(files):
                m = re.match(r"(seg\d+)_video\.mp4$", fname)
                if not m:
                    continue
                seg = m.group(1)
                ep_dir = os.path.relpath(root, task_dir)
                segments.append({
                    "task": task,
                    "episode": ep_dir,
                    "seg": seg,
                    "path": os.path.join(root, fname),
                })
    segments.sort(key=lambda s: f"{s['task']}/{s['episode']}/{s['seg']}")
    return segments


def _expand_task_spec(task_spec: str, default_tasks: list[str]) -> list[str]:
    """Resolve CLI task spec to short task names used by pair generators."""
    task_groups = {
        "all": default_tasks,
        "training": default_tasks,
        "inspire": [t for t in ALL_TASKS if "G1_WBT_Inspire_" in t],
        "brainco": [t for t in ALL_TASKS if "G1_WBT_Brainco_" in t],
    }
    key = task_spec.lower()
    if key in task_groups:
        return [t.replace("G1_WBT_", "") for t in task_groups[key]]
    return [t.strip() for t in task_spec.split(",") if t.strip()]


def make_pairs_from_segments(segments: list[dict]) -> list[dict]:
    pairs = []
    for s in segments:
        for ci in range(CLIPS_PER_SEG):
            pairs.append({
                "task": s["task"],
                "episode": s["episode"],
                "seg": s["seg"],
                "seg_path": s["path"],
                "clip": ci,
                "start": ci * CLIP_DURATION,
                "source_id": f"{s['task']}/{s['episode']}/{s['seg']}_c{ci}",
            })
    return pairs


def _write_jsonl(path: str, rows: list[dict]):
    with open(path, "w") as fh:
        for row in rows:
            fh.write(json.dumps(row, sort_keys=True) + "\n")


# ── process one pair ─────────────────────────────────────────────────

def process_pair(p: dict) -> dict:
    os.makedirs(os.path.dirname(p["out_tgt"]), exist_ok=True)
    os.makedirs(os.path.dirname(p["out_ctx"]), exist_ok=True)

    if not os.path.isfile(p["out_tgt"]):
        cut_clip(p["seg_path"], p["out_tgt"], p["start"])
    if not os.path.isfile(p["out_ctx"]):
        # identity reconstruction: control == target, byte-for-byte
        shutil.copyfile(p["out_tgt"], p["out_ctx"])

    return {
        "video": p["rel_tgt"],
        "prompt": PROMPT,
        "control_video": p["rel_ctx"],
    }


# ── main ─────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Generate robot→robot reconstruction pairs from segments")
    ap.add_argument("--task", required=True,
                    help="task short name, comma-separated, or 'all'")
    ap.add_argument("--max-segments", type=int, default=0,
                    help="max segments per task (0 = unlimited)")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--clean", action="store_true",
                    help="remove existing pair/identity_r2r/1s/ before writing")
    args = ap.parse_args()

    tasks = _expand_task_spec(args.task, TRAINING_TASKS)

    sec_dir = os.path.join(PAIR_DIR, "identity_r2r", "1s")
    if args.clean and os.path.isdir(sec_dir):
        shutil.rmtree(sec_dir)

    print("Make Robot Pair (identity reconstruction, ctrl == tgt)")
    print(f"  tasks:         {tasks}")
    print(f"  max-segments:  {args.max_segments or 'unlimited'}")
    print(f"  seed:          {args.seed}")
    print(f"  workers:       {args.workers}")

    all_segs = find_segments(tasks)
    print(f"  found {len(all_segs)} segments across {len(tasks)} tasks")

    if args.max_segments > 0:
        by_task: dict[str, list[dict]] = {}
        for s in all_segs:
            by_task.setdefault(s["task"], []).append(s)
        sampled = []
        for task in sorted(by_task.keys()):
            segs = by_task[task]
            rng = random.Random(f"{args.seed}:sample:{task}")
            rng.shuffle(segs)
            sampled.extend(segs[:args.max_segments])
        all_segs = sampled
        print(f"  sampled → {len(all_segs)} segments")

    all_pairs = make_pairs_from_segments(all_segs)
    if not all_pairs:
        print("No pairs generated, exiting")
        return

    print(f"  {len(all_pairs)} pairs")

    to_process: list[dict] = []
    by_task: dict[str, list[dict]] = {}
    for p in all_pairs:
        by_task.setdefault(p["task"], []).append(p)

    for task, task_pairs in sorted(by_task.items()):
        if not task_pairs:
            continue
        task_dir = os.path.join(sec_dir, task)
        video_dir = os.path.join(task_dir, "video")
        ctrl_dir = os.path.join(task_dir, "control_video")
        os.makedirs(video_dir, exist_ok=True)
        os.makedirs(ctrl_dir, exist_ok=True)

        for idx, p in enumerate(sorted(task_pairs, key=lambda x: x["source_id"])):
            name = f"pair_{idx:04d}.mp4"
            p["out_tgt"] = os.path.join(video_dir, name)
            p["out_ctx"] = os.path.join(ctrl_dir, name)
            p["rel_tgt"] = f"video/{name}"
            p["rel_ctx"] = f"control_video/{name}"
            p["manifest"] = {
                "data_type": "identity_r2r",
                "duration": "1s",
                "robot_task": p["task"],
                "task": p["task"],
                "episode": p["episode"],
                "seg": p["seg"],
                "clip_idx": p["clip"],
                "source_segment_id": f"{p['task']}/{p['episode']}/{p['seg']}",
                "source_id": p["source_id"],
                "seg_path": p["seg_path"],
                "video": f"video/{name}",
                "control_video": f"control_video/{name}",
                "input_role": "robot",
                "target_role": "robot",
            }
            to_process.append(p)

    t0 = time.time()
    task_meta: dict[str, list[dict]] = {task: [] for task in by_task}
    task_manifest: dict[str, list[dict]] = {task: [] for task in by_task}

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {
            pool.submit(process_pair, p): p for p in to_process
        }
        done = 0
        total = len(to_process)
        for fut in as_completed(futures):
            p = futures[fut]
            meta = fut.result()
            task_meta[p["task"]].append(meta)
            task_manifest[p["task"]].append(p["manifest"])
            done += 1
            if done % 50 == 0 or done == total:
                print(f"  {done}/{total}", flush=True)

    print(f"  clips done in {time.time() - t0:.1f}s")

    index_rows: list[dict] = []
    for task, metas in task_meta.items():
        if not metas:
            continue
        metas.sort(key=lambda m: m["video"])
        task_dir = os.path.join(sec_dir, task)
        csv_path = os.path.join(task_dir, "metadata.csv")
        with open(csv_path, "w", newline="") as f:
            writer = csv.DictWriter(
                f, fieldnames=["video", "prompt", "control_video"])
            writer.writeheader()
            writer.writerows(metas)
        print(f"  metadata: {csv_path} ({len(metas)} rows)")
        manifest_rows = sorted(task_manifest[task], key=lambda m: m["source_id"])
        manifest_path = os.path.join(task_dir, "manifest.jsonl")
        _write_jsonl(manifest_path, manifest_rows)
        index_rows.extend(manifest_rows)
        print(f"  manifest: {manifest_path} ({len(manifest_rows)} rows)")

    index_path = os.path.join(sec_dir, "index.jsonl")
    _write_jsonl(index_path, sorted(index_rows, key=lambda m: m["source_id"]))
    print(f"  index: {index_path} ({len(index_rows)} entries)")

    print(f"\nDone")


if __name__ == "__main__":
    main()
